name: Java Bruno

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Instalando JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Compilar o Teste
      run: javac -cp src src/Teste.java
      
    - name: Compilar o Projeto
      run: javac -cp src src/Main.java
    
    
    - name: Executnado o Teste
      run: |
        cd src
        java Teste
